# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.6.2"

            - name: Install dependencies
              run: npm i --save-dev @craco/craco && npm i . --force

            - name: Publish
              run: npm run build
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.6.2"

            - name: Install dependencies
              run: npm i . --force

            - name: Publish
              run: npm i --save-dev @craco/craco && npm run build --x64 --ia32 -l
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    mac:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.6.2"

            - name: Install dependencies
              run: npm i --save-dev @craco/craco && npm i . --force

            - name: Publish
              run: npm run build --x64 -m
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
